;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Graph Controls]
Pos=27,46
Size=329,266
Collapsed=1

[Window][Graph Settings]
Pos=30,7
Size=407,224
Collapsed=0

[Window][Node Details]
Pos=60,60
Size=1288,714
Collapsed=1

[Table][0xB596925D,5]
Column 0  Weight=1.0000
Column 1  Weight=1.0000
Column 2  Weight=1.0000
Column 3  Weight=1.0000
Column 4  Weight=1.0000

[Docking][Data]

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
