name: bike-fit
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pytorch>=2.1.0
  - torchvision
  - cudatoolkit=11.8
  - flask>=3.0.0
  - numpy>=1.24.0
  - opencv>=4.8.0
  - pillow>=10.0.0
  - scipy>=1.7.1
  - tensorflow>=2.15.0
  - pip:
    - transformers>=4.36.0
    - accelerate>=0.27.0
    - bitsandbytes>=0.41.0
    - huggingface-hub>=0.19.0
    - sentencepiece>=0.1.99
    - mediapipe>=0.10.5
    - websockets==10.0
    - python-engineio==4.2.1
    - python-socketio==5.4.0
    - SQLAlchemy==1.4.23
    - python-dotenv>=1.0.0
    - pytest==6.2.5
    - pytest-cov==2.12.1
    - requests==2.26.0
    - tensorflow-hub>=0.15.0
    - kagglehub>=0.3.6
    - moviepy>=1.0.3
    - openai>=1.3.0
    - aiohttp>=3.8.0
    - async-timeout>=4.0.0
    - tqdm>=4.66.0
    - flask-cors 